### PR TITLE
Add a batch mode + Conversion limit calculation

### PR DESCRIPTION
**Pull request by wizz13150**
Hey, 

as mentionned here : https://github.com/AUTOMATIC1111/stable-diffusion-webui-tensorrt/issues/30

A batch mode would be appreciated.

Obviously not a python expert, lol. 

Add a checkbox to activate batch mode.
Add a field for a folder containing models to convert. Both tab.
_EDIT_: Using "models/Stable-diffusion" and "models/Unet-onnx" as default, if leaved empty.
Add some basic logging into the console, kind of blind right now, wondering if it's dead or alive when converting to onnx, and what is going on.
_EDIT_: Add a Calculation to display the limit allowed for ONNX to TRT conversion. Should still work as the limit is going up, eventually, as well.

Screen for the 'Convert to ONNX' tab :

image

image
<br>

Screen for the 'Convert ONNX to TensorRT' tab  : 

image

image

It will process all the files in the folder as well. I mean, it worked for me, lol.
<br>

Cheers ! 🥂

### CODE REVIEW

**Comment by jebarpg** [comment]
Hey I don't know how to get in touch with you other than here, but I also know how to fix an issue with the 
" Error[4]: [shapeCompiler.cpp::nvinfer1::builder::DynamicSlotBuilder::evaluateShapeChecks::1276] Error Code 4: Internal Error (kOPT values for profile 0 violate shape constraints: /input_blocks.1/input_blocks.1.1/transformer_blocks.0/attn1/Einsum_output_0: tensor volume exceeds (2^31)-1, dimensions are [(* 8 batch_size),E0,E0] where E0=(* height width) Volume exceeds 2^31-1.)"


type of error.
so basically what I have found is the --maxShapes has to have a product less than or equal to 92160.
so basically what we need to do is on the Convert ONNX to TensorRT when the sliders for Maximum width, Maximum height, Maximum batch size are changed, (I did a little digging and found gradio.slider.change() method) 

then calculate the total size to see if it is <= 92160 or not and if greater than then prevent the slider from moving any further and maybe prompting the user saying that they have exceed the shape constraints. or something that would make sense to the average person to let them know they can't generate with that high of parameters. This would have to be checked for the three sliders: 

Maximum width 
Maximum height
Maximum batch size

I am not quite sure where to put this logic or how to correctly solve it using the UI module. I would like to learn if you could help or if you think this is something you could fix and don't have time to teach that could work too... 
 
To note the --maxShapes=Bx?xHxW 
B=max batch size
?= I don't know what this is suppose to be for, but none of the sliders effect this and it is always 4 (i believe... caveat I could have missed something but I am pretty sure this never changes)
H=max height
W=max width

the B value on the slider is translated to its value times 2 so if you have max batch size at 5 then 5 * 2 = 10 
the H and W values on the slider are translated to their Value / 8 
thus 
if the value of W is 960 then the value generated on the --maxShapes is 960/8=120
so what we need to do is the following:
B = max batch size * 2
? = 4
H = max height / 8
W = max width / 8
if( B\*?\*H\*W > 92160) prevent the slider from moving and move it back to the previous value. and optionally prompt user letting them know why the slider isn't going any further. else let the slider act normally.

**Comment by jebarpg** [comment]
Also it doesn't make sense to me to not have (in the 'Convert ONNX to TensorRT' tab) a drop down menu which lists all the onnx models in the default onnx models directory (models/Unet-onnx/). the text field can be left there, but above it would be more effective to have a drop down menu which pulls from the default onnx directory with a refresh button to update. and then when selecting from the drop down menu populate the 'Onnx model filename' text box with the path text of the selected model.

It's error prone to always have to type out the correct path and filename of the onnx model.
models/Unet-onnx/onnx-model-filename.onnx
but leaving the text field keeps the flexibility open for users to enter in a particular custom path if they so choose.

**Comment by jebarpg** [comment]
Also thank you for the batch runner!!!... should have said this first XD mb

**Comment by jebarpg** [comment]
also you need to add:
if file.endswith(".safetensors") or file.endswith(".ckpt"):
after line 20 in ui_trt.py
lol I was just running it and I have png files in there so I can see preview images of my checkpoints and the batch conversion was converting png files to onnx lol.

**Comment by jebarpg** [comment]
I modified your export_unet_to_onnx code to only convert files from the batch_directory if they don't already exist in the models/Unet-onnx/ directory. I left the print statement to see the list of onnx_files and the onnx_files_to_process (which is the difference between the onnx and batch directories. I also add the batch_file.endswith(".safetensors") or batch_file.endswith(".ckpt") to filter out any files other than models extensions in the batch directory. Like mentioned above I have pngs in the batch directory next to my models for previewing them in SD. 

```python
def export_unet_to_onnx(filename, opset, batch_run, batch_directory):
    print(f'Starting Conversion to .onnx')
    if batch_run:
        print(f"Batch Models mode")  # Debug line
        onnx_files = os.listdir(os.path.join(paths_internal.models_path, "Unet-onnx/"))
        print(onnx_files)
        onnx_files_to_process = list()
        for batch_file in os.listdir(batch_directory):
            add_flag = True
            for onnx_file in onnx_files:
                if batch_file.split('.')[0] == onnx_file.split('.')[0]:
                    add_flag = False
            if add_flag and (batch_file.endswith(".safetensors") or batch_file.endswith(".ckpt")):
                onnx_files_to_process.append(batch_file)
        print(onnx_files_to_process)
        for file in onnx_files_to_process:
            print(f"Converting model file: {file}")  # Debug line
            modelname = os.path.splitext(file)[0] + ".onnx"
            onnx_filename = os.path.join(paths_internal.models_path, "Unet-onnx", modelname)            
            print(f"Target ONNX filename: {onnx_filename}")  # Debug line
            export_onnx.export_current_unet_to_onnx(onnx_filename, opset)

        return f'Batch conversion completed for files in {batch_directory}', ''
    else:
        print(f"Single Model mode")  # Debug line
        if not filename:
            modelname = shared.sd_model.sd_checkpoint_info.model_name + ".onnx"
            filename = os.path.join(paths_internal.models_path, "Unet-onnx", modelname)
        print(f"Target ONNX filename: {filename}")  # Debug line
        
        export_onnx.export_current_unet_to_onnx(filename, opset)

        return f'Done! Model saved as {filename}', ''
```

**Comment by wizz13150** [comment]
Heyy,

thanks for your involvement (: 
This is a one time process, that's why I tried to stay as simple as possible on purpose, to let every doors open.

> Volume exceeds 2^31-1

Not sure where we are going with this "low" value, if they did it on purpose to send a big middle finger to the open source world, or ..?!
Probably just to sell us the 'complete' one after... 
<br>

> then calculate the total size to see if it is <= 92160 or not and if greater than then prevent the slider from moving any further and maybe prompting the user saying that they have exceed the shape constraints.

That's a good idea ! Should be implemented indeed. Will see this first
<br>

> Also thank you for the batch runner!!!

image
<br>

> if file.endswith(".safetensors") or file.endswith(".ckpt"):
> I was just running it and I have png files in there so

Yeah, I was starting with this at first, then removed it for some reasons, not sure which one lol. Should probably be there yeah..
<br>

> I modified your export_unet_to_onnx code to only convert files from the batch_directory if they don't already exist in the models/Unet-onnx/ directory. I left the print statement to see the list of onnx_files and the onnx_files_to_process (which is the difference between the onnx and batch directories. I also add the batch_file.endswith(".safetensors") or batch_file.endswith(".ckpt") to filter out any files other than models extensions in the batch directory.

And great, thanks for that ! 
(the 'models\Unet-onnx' folder need to exist in this edited function, should add a control for this)
I'll touch it later, the idea is nice.
<br>

Cheers ! 🥂

**Comment by wizz13150** [comment]
Here is an update.

To 'fix' the unet to onnx export function : 
- Only looks for the .safetensors and .ckpt files as well.
- It won't process models that already are in the 'Unet-onnx' folder as well.
- List files to be processed
<br>

In the 'Convert ONNX to TensorRT' tab : 
- Add a 'Calculate values limit for conversion' button.
- Add a Label below to display the current value and the high limit. Screenshot below.
<br>

Not sure if it's the best approach, seems kind of tricky to print values dynamically in gradio.
Again, I went for a simple method. Feel free to tell me how to do, or to do it.

Assuming some values in the calculation at this point, only following the informations in your message above, may be incorrect, didn't dig further.
I now knows that the 'unknown' value is the "allowed dimensions" value, still fixed tho.
So let's just say 'Who cares?' about the name, lol. 🙃

Here is the calculation function : 

```
def calculate_and_check_constraints(max_width, max_height, max_batch_size):
    B = max_batch_size * 2
    unknown = 4
    H = max_height / 8
    W = max_width / 8

    calculated_value = int(B * unknown * H * W)

    return f"{calculated_value} / 92160", ""
```

Here is a screen :

image

32768 is the default value, for the default settings. (2x4x64x64)
I get "86528 / 92160" using 832*832, so looks good to me, as the limit seems to be correct (for me too).

And the "Maximum prompt token count" doesn't seems to have any weight here. (or negligible?)
I can run it at max value, using 832*832 and "Maximum batch size" at 1.
Need the complete formula, if there is one.

**Still purely informative, won't block the conversion process in any way.**

Cheers ! 🥂

**Comment by wizz13150** [comment]
Okay, fixed and tested further.

Will also now use "models/Stable-diffusion" and "models/Unet-onnx" folders as source, if the field is empty.

Same logic extended to the 'OnnxToTRT' function :
- Only looks for the .onnx files as well.
- It won't process models that already are in the 'Unet-trt' folder as well.
- List files to be processed.

'Convert to ONNX' : 

image


'Convert ONNX to TensorRT' : 

image
<br>

No change to the calculation part.

Should be good this time.

image

Cheers ! 🥂

**Comment by jebarpg** [comment]
Awesome :D You're pretty cool in my book!! 

    Not sure if it's the best approach, seems kind of tricky to print values dynamically in gradio.
    Again, I went for a simple method. Feel free to tell me how to do, or to do it.

Ya simple is always good, and the dynamic in gradio was were I was getting stuck as well.

    I now knows that the 'unknown' value is the "allowed dimensions" value, still fixed tho.

this is good to know thanks.

    So let's just say 'Who cares?' about the name, lol. 🙃

lol agreed :)

    And the "Maximum prompt token count" doesn't seems to have any weight here. (or negligible?)
    I can run it at max value, using 832*832 and "Maximum batch size" at 1.

Yea the Maximum prompt token count didn't have any effect on my testing as well. When you max it out the --maxShapes= values don't change at all. I spent like 2 hours just testing all different possible combinations of the sliders and keeping a spread sheet of the results of running the command if it errored or if it worked. 

I personally don't recommend having a batch size any larger than 1 or 2 actually, I did the calculations and found the factors of the remainders of what would be left of the shape and at batch size 2 you could only have an image width and height of 576 x 640 or 640 x 576 and at batch size 3 you can only do 480x512 or 512x480 which puts the lower number less than 512. 

here is how you figure out how the batch size impacts your remaining width and height size left to fiddle with:

B = batch size * 2 
A = 4 (allowed dimensions)
H = ?
W = ?

I'm going to let batch size = 3 for this example:
we know 92160 is the max value we can have so we take 92160 / (B * A) = _F_ => 92160 / ((3 *2) * 4) = 3840
Take _F_ google search for "factors of _F_" for example "factors of 3840" 
Google will return a list of factors e.g. for 3840 we get "1, 2, 3, 4, 5, 6, 8, 10, 12, 15, 16, 20, 24, 30, 32, 40, 48, 60, 64, 80, 96, 120, 128, 160, 192, 240, 256, 320, 384, 480, 640, 768, 960, 1280, 1920, 3840"
now find the middle two numbers, I use notepad++ and do a find and replace with regex and replace all the commas ',' with a new line '\n' then see the line count (in this case there are 36 lines thus 36 factors) and then divide by 2 you get 18 so the 18th number is 60 which is our lower width or height value and then take the next higher number 19th which is 64 this is our higher width or height value.

then like in the equation i gave you above since we were dividing by 8 to get the max width/height values from --maxShapes numbers we want to go the other direction so we multiply by 8, so for the two numbers we got 60 and 64 we get
60 * 8 = 480
64 * 8 = 512
at a batch size of 3

I personally think I will create two versions of each model to their trt version. one at a max width of 960 and max height at 768 and one at max width of 768 and max height at 960. This will allow for a 16:9 and 9:16 if you have a width or height at 512 and a width or height at 910, which those two values are within the 960 and 786 values. And you can get pretty much all other AR (aspect ratios) within the bounds of 960 and 768 so it covers pretty much all size cases you would generally want. I might even go so far as to have some text label recommending this for people so that they don't have to think about it as much if they just want to go with the recommendations. Or never see our discussion in the repo logs.

I am think about having the shape added to the new output file name as an option or a check box you can choose to click to add it to the default name. 

    Need the complete formula, if there is one.

Ya I posted the question on the TensorRT repo hoping they get back to me eventually.

It's fun to work with ya! 

Cheers!

**Comment by wizz13150** [comment]
> 60 * 8 = 480
> 64 * 8 = 512
> at a batch size of 2

🤔 Is that 'max' values, or just an example ? 
Just to be sure, cause playing sith sliders allows me to catch the limit.
<br>

Here is a screen, to catch  640*576, at batch_size = 2 : 

image

I just launched one to be sure, and it seems to works, if i don't edit this, it means that the conversion ended as expected.

image


> I might even go so far as to have some text label recommending this for people so that they don't have to think about it as much if they just want to go with the recommendations. Or never see our discussion in the repo logs.

Suggestions in the UI is also a good idea !

I did leave the 'unknown' var on purpose, for now. Some mystery is always fun. 😂

Cheers ! 🥂

**Comment by jebarpg** [comment]
Actually sorry I was using a batch size of 3... I got mixed up because I did a batch size of 2 calculation first then did a one with 3 and forgot which one I googled searched for and swapped 2 for 3... by bad. try batch size of 3 instead and the rest should be the same in my calculations.

**Comment by jebarpg** [comment]
Also updated the comment with 3 instead of 2 for future reference.

**Comment by wizz13150** [comment]
Okay, it's all good.

I just launched again, roughly touching the 92160 limit with 640*576, **_and_** touching the max token limit -randomly- at 525.
It's running fine as well.

So i think we can assume here that there is absolutely no impact in the equation.

**Comment by jebarpg** [comment]
I reviewed the changes and everything looks great! I would recommend for visual sake putting a print('\n') before and after we print out the files to process. But everything looks good

**Review by jebarpg — APPROVED** [review]
Looks good!

**Comment by wizz13150** [comment]
> I would recommend for visual sake putting a print('\n') before and after we print out the files to process.

Not false (: 

Also, for posterity,
I'm not sure about the why of the first one, but still to fix, in some way : 
- Will crash when converting to ONNX in batch mode, with a model currently loaded that is linked to a .trt file.
It's happening right after the first conversion: 

The issue is related to `export_onnx.py`

I have to un-link the model from the trt file, from settings (below) or renaming the 'Unet-trt' folder, to run Unet to ONNX in batch mode.

image



- **[FIXED]** 'filename' fields should be ignored if **not** empty **_and_** batch mode is activated. It will use the _non-empty_ filename path even if the batch mode is selected.

and:

- I can't remember, will edit this.
- I remember, running the limit calculation on a different thread, to get a result even if the console is working on something.

**Review by jebarpg — COMMENTED** [review]
line 22 and 71 aren't needed. they have no effect inside the if statement. did you mean to put them in the else part ?

**Comment by wizz13150** [comment]
Indeed, was pretty dumb. 
Fixed in the right way, will ignore the non-empty filename if batch_run is true.

And display adjustment :

image

I'll probably open a new clean PR at the end, lol.

**Comment by wizz13150** [comment]
:hide:

Was targeting the wrong folder during the batch conversion to ONNX...

Still to fix:
- Running the limit calculation on a different thread, to get a result even if the console is working on something.
- To not crash when converting to ONNX in batch mode, with a model currently loaded that is linked to a .trt file.
It's happening right after the first conversion:
The issue is related to `export_onnx.py` and unet activation/desactivation

**Comment by jebarpg** [comment]
oops hehe

**Comment by darongma** [comment]
You guys are awesome!

**Comment by wizz13150** [comment]
And one more. 😂

Fixed:
- Run the calculate function as async, still tricky with gradio. Will work if the console is already converting or working.
- Don't block anymore if files_to_process is empty, in batch mode, leave the function and print a message to say so. Both functions.
image

- Console display adjustments, code comments to be readable.

The only thing Still ToDo (as i can tell) :
- To not crash when converting to ONNX, with a model currently loaded that is linked to a .trt file/unet.
The issue is related to export_onnx.py and 'attention optimization' desactivation and seems **_not related to my commits_**.
image

- Remove unused params in `export_trt.py`, from previous bad approach.

Let's see this one, i'm afraid i'll have to edit the other file for this.
Not sure yet how to take this one, tho. 🤨🤔

Amazing, the number of bugs for a simple batch mode 😂 A robust logic is more complicated than expected, lol
Not just _a checkbox and a field_.
The next one should finally be the last commit, i'll then open a new PR for this mess, in a single commit..

**Comment by wizz13150** [comment]
Last commit to fix an introduced bad targetting.
Clean the code.

I'll now open a new clean PR. 
See you there.

**Comment by wizz13150** [comment]
Last commit to fix an introduced bad targetting.
Clean the code.

Not sure if i should touch the last bug, as it's not related to my commits.
Will see later.

I'll now open a new clean PR.
See you there.

**Pull request closed without merging**
